### ISSUE TITLE
Tutorial needs to be upgraded to user v 0.20.0 to show new use Apollo Client v3 Cache Behavior for GraphQL Mutations

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood-tutorial#1]
Currently on 19.5 canary but needs rework to show:

Apollo Client v3 Cache Behavior for GraphQL Mutations

Prior to this version, Redwood Cells used Apollo’s cache and network fetch policy. This has been removed in favor of the default policy (see #1250 6). This change, along with the new Apollo v3 behavior, changes the behavior of mutations — state changes will often not render without a page reload.

Unless Tutorial 2.0 will be replacing this.

**Comment by cannikin** [comment]
@thedavidprice @jtoar @peterp @mojombo What do we want to do about this? I believe our options are:

1. Try to find some combination of Apollo cache policy that brings back the old behavior
2. Use `location.href` when redirecting instead of `navigate` (which will cause the entire app to reload)
3. Manually tell Apollo to [refetch](https://www.apollographql.com/docs/react/data/queries/#refetching) on create/delete pages, but this has shown to cause issues with the Loading state (you need to manage it yourself when refetching)
4. Show the user how to write their own cache management code 😐
5. Use @jtoar's [technique](https://community.redwoodjs.com/t/configuring-inmemorycache-or-making-updates-to-the-cache-more-tractable/1312)
6. Rollback to Apollo 2 (from the testing I did Apollo 3 didn't have significantly smaller filesizes)

We should think about this carefully as the wrong one will be incompatible with urQL and we'll have to change it again. :(

**Comment by cannikin** [comment]
Maybe for generated scaffolds we add a `beforeQuery` and use `no-cache` to disable the cache completely. Each time you go back to the index page it would run the query again from scratch, but it's transparent to the user and, especially during the tutorial, the load time would be negligible as it's local and you' only creating a few records

**Comment by Tobbe** [comment]
I implemented my own GraphQL Client for fun in Redwood (replacing AC3) with no caching at all. The only thing that "breaks" in the tutorial is deleting a post when on the list view (http://localhost:8910/admin/posts). We'd have to trigger a reload of the page.

**Comment by cannikin** [comment]
Hopefully we patched Redwood itself to keep the tutorial working as currently written! https://github.com/redwoodjs/redwood/pull/1428
